let product = [
  {
    id: 1,
    title: 'Takumi Sen',
    price: '$400',
    imgSrc: [
      'img/imgIn/Y-3 Takumi Sen/i-main.avif',
      'img/imgIn/Y-3 Takumi Sen/i-1.avif',
      'img/imgIn/Y-3 Takumi Sen/i-2.avif',
      'img/imgIn/Y-3 Takumi Sen/i-3.avif',
      'img/imgIn/Y-3 Takumi Sen/i-4.avif',
      'img/imgIn/Y-3 Takumi Sen/i-bag.avif',
    ],
    colors: 'Black',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 2,
    title: 'ITOGO',
    price: '$600',
    imgSrc: [
      'img/imgIn/Y-3 ITOGO/i-main.avif',
      'img/imgIn/Y-3 ITOGO/i-1.avif',
      'img/imgIn/Y-3 ITOGO/i-2.avif',
      'img/imgIn/Y-3 ITOGO/i-3.avif',
      'img/imgIn/Y-3 ITOGO/i-4.avif',
      'img/imgIn/Y-3 ITOGO/i-bag.avif',
    ],
    colors: 'Blue',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 3,
    title: 'Sportswear',
    price: '$280',
    imgSrc: [
      'img/imgIn/adidas by Stella McCartney/i-main.avif',
      'img/imgIn/adidas by Stella McCartney/i-1.avif',
      'img/imgIn/adidas by Stella McCartney/i-2.avif',
      'img/imgIn/adidas by Stella McCartney/i-3.avif',
      'img/imgIn/adidas by Stella McCartney/i-4.avif',
      'img/imgIn/adidas by Stella McCartney/i-bag.avif',
    ],
    colors: 'Cloud White',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 4,
    title: 'Seeulater',
    price: '$220',
    imgSrc: [
      'img/imgIn/Seeulater/i-main.avif',
      'img/imgIn/Seeulater/i-1.avif',
      'img/imgIn/Seeulater/i-2.avif',
      'img/imgIn/Seeulater/i-3.avif',
      'img/imgIn/Seeulater/i-4.avif',
      'img/imgIn/Seeulater/i-bag.avif',
    ],
    colors: 'Unity Orange',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 5,
    title: '4DFWD',
    price: '$200',
    imgSrc: [
      'img/imgIn/4DFWD/i-main.avif',
      'img/imgIn/4DFWD/i-1.avif',
      'img/imgIn/4DFWD/i-2.avif',
      'img/imgIn/4DFWD/i-3.avif',
      'img/imgIn/4DFWD/i-4.avif',
      'img/imgIn/4DFWD/i-bag.avif',
    ],
    colors: 'Solar Red',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 6,
    title: 'Roverend',
    price: '$200',
    imgSrc: [
      'img/imgIn/Roverend/i-main.avif',
      'img/imgIn/Roverend/i-1.avif',
      'img/imgIn/Roverend/i-2.avif',
      'img/imgIn/Roverend/i-3.avif',
      'img/imgIn/Roverend/i-4.avif',
      'img/imgIn/Roverend/i-bag.avif',
    ],
    colors: 'Halo Blush',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 7,
    title: 'ULTRABOOST LIGHT',
    price: '$190',
    imgSrc: [
      'img/imgIn/ULTRABOOST LIGHT/i-main.avif',
      'img/imgIn/ULTRABOOST LIGHT/i-1.avif',
      'img/imgIn/ULTRABOOST LIGHT/i-2.avif',
      'img/imgIn/ULTRABOOST LIGHT/i-3.avif',
      'img/imgIn/ULTRABOOST LIGHT/i-4.avif',
      'img/imgIn/ULTRABOOST LIGHT/i-bag.avif',
    ],
    colors: 'Lucid Lemon',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 8,
    title: 'Rivalry',
    price: '$300',
    imgSrc: [
      'img/imgIn/Rivalry/i-main.avif',
      'img/imgIn/Rivalry/i-1.avif',
      'img/imgIn/Rivalry/i-2.avif',
      'img/imgIn/Rivalry/i-3.avif',
      'img/imgIn/Rivalry/i-4.avif',
      'img/imgIn/Rivalry/i-bag.avif',
    ],
    colors: 'Black',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 9,
    title: 'Court Slip-On',
    price: '$180',
    imgSrc: [
      'img/imgIn/Court Slip-On/i-main.avif',
      'img/imgIn/Court Slip-On/i-1.avif',
      'img/imgIn/Court Slip-On/i-2.avif',
      'img/imgIn/Court Slip-On/i-3.avif',
      'img/imgIn/Court Slip-On/i-4.avif',
      'img/imgIn/Court Slip-On/i-bag.avif',
    ],
    colors: 'Core Black',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 10,
    title: 'Orketro',
    price: '$160',
    imgSrc: [
      'img/imgIn/Orketro/i-main.avif',
      'img/imgIn/Orketro/i-1.avif',
      'img/imgIn/Orketro/i-2.avif',
      'img/imgIn/Orketro/i-3.avif',
      'img/imgIn/Orketro/i-4.avif',
      'img/imgIn/Orketro/i-bag.avif',
    ],
    colors: 'Core Black',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 11,
    title: 'Harden Volume',
    price: '$160',
    imgSrc: [
      'img/imgIn/Harden Volume/i-main.avif',
      'img/imgIn/Harden Volume/i-1.avif',
      'img/imgIn/Harden Volume/i-2.avif',
      'img/imgIn/Harden Volume/i-3.avif',
      'img/imgIn/Harden Volume/i-4.avif',
      'img/imgIn/Harden Volume/i-bag.avif',
    ],
    colors: 'Cloud White',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 12,
    title: 'Cushion',
    price: '$150',
    imgSrc: [
      'img/imgIn/Cushion/i-main.avif',
      'img/imgIn/Cushion/i-1.avif',
      'img/imgIn/Cushion/i-2.avif',
      'img/imgIn/Cushion/i-3.avif',
      'img/imgIn/Cushion/i-4.avif',
      'img/imgIn/Cushion/i-bag.avif',
    ],
    colors: 'Gold Metallic',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 13,
    title: 'Mahomes 1 Impact FLX',
    price: '$140',
    imgSrc: [
      'img/imgIn/Mahomes 1 Impact FLX/i-main.avif',
      'img/imgIn/Mahomes 1 Impact FLX/i-1.avif',
      'img/imgIn/Mahomes 1 Impact FLX/i-2.avif',
      'img/imgIn/Mahomes 1 Impact FLX/i-3.avif',
      'img/imgIn/Mahomes 1 Impact FLX/i-4.avif',
      'img/imgIn/Mahomes 1 Impact FLX/i-bag.avif',
    ],
    colors: 'Solar Orange',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 14,
    title: 'Stan Smith Crepe',
    price: '$145',
    imgSrc: [
      'img/imgIn/Stan Smith Crepe/i-main.avif',
      'img/imgIn/Stan Smith Crepe/i-1.avif',
      'img/imgIn/Stan Smith Crepe/i-2.avif',
      'img/imgIn/Stan Smith Crepe/i-3.avif',
      'img/imgIn/Stan Smith Crepe/i-4.avif',
      'img/imgIn/Stan Smith Crepe/i-bag.avif',
    ],
    colors: 'Core Black',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 15,
    title: 'Adifom Climacool',
    price: '$120',
    imgSrc: [
      'img/imgIn/Adifom Climacool/i-main.avif',
      'img/imgIn/Adifom Climacool/i-1.avif',
      'img/imgIn/Adifom Climacool/i-2.avif',
      'img/imgIn/Adifom Climacool/i-3.avif',
      'img/imgIn/Adifom Climacool/i-4.avif',
      'img/imgIn/Adifom Climacool/i-bag.avif',
    ],
    colors: 'Core Black',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 16,
    title: 'Rivalry Low TR',
    price: '$110',
    imgSrc: [
      'img/imgIn/Rivalry Low TR/i-main.avif',
      'img/imgIn/Rivalry Low TR/i-1.avif',
      'img/imgIn/Rivalry Low TR/i-2.avif',
      'img/imgIn/Rivalry Low TR/i-3.avif',
      'img/imgIn/Rivalry Low TR/i-4.avif',
      'img/imgIn/Rivalry Low TR/i-bag.avif',
    ],
    colors: 'Semi Coral Fusion',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
]
